Touch up read me
orion-junkins/adam-gpt pull request #10
Opened 2023-05-25 22:28 UTC by stalberm

2023-05-26 02:09 UTC, orion-junkins approved these changes, later dismissed

2023-06-07 03:32 UTC, orion-junkins requested changes
Remove the extra pycache file, guessing that doesn't need to be there? Then I am happy with merging this :)

Thanks for updating!

2023-06-07 05:18 UTC, kimberlymarkley commented
pycache removed!

2023-06-07 14:36 UTC, orion-junkins approved these changes
Looks great!

2023-06-07 17:51 UTC, swearingenmj approved these changes

2023-06-07 17:51 UTC, merged